docker reproducible wip

diff --git a/zkVM/sp1/justfile b/zkVM/sp1/justfile
--- a/zkVM/sp1/justfile
+++ b/zkVM/sp1/justfile
@@ -46,6 +46,24 @@ build-elf:
         echo "✅ ELF Exists, skipping SP1 build"; \
     fi
 
+
+# Build only the zkVM ELF program using sp1 docker (bitwise identical ELFs)
+build-elf-reproducible:
+    if ! {{ path_exists(cargo-prove-path) }}; then \
+        echo -e "⛔ Missing zkVM Compiler.\nRun \`just initial-config-installs\` to prepare your environment"; \
+        exit 1; \
+    fi; \
+    source {{ env-settings }}; \
+    if [ ! -f "$ZK_PROGRAM_REPRODUCIBLE_ELF_PATH" ]; then \
+        echo -e "Can't find ELF at \`$ZK_PROGRAM_REPRODUCIBLE_ELF_PATH\`.\nAttempting to build it..."; \
+        RUSTFLAGS="-Copt-level=3 -Clto=fat -Ccodegen-units=1 -Cdebuginfo=1 -Cembed-bitcode=yes" \
+        echo -r "\n******\nNOTE: the first run will download an sp1 docker image ~5GB\ncheck network usage if you are not seeing any progress on this step...\n"; \
+        RUSTFLAGS="-Copt-level=3 -Clto=fat -Ccodegen-units=1 -Cdebuginfo=1 -Cembed-bitcode=yes" cargo prove build --docker -p chacha-program; \
+    else \
+        echo "✅ ELF Exists, skipping SP1 build"; \
+    fi
+
+
 # Run the proxy in release mode with debug logs
 run-release *FLAGS: build-elf
     RUST_LOG=pda_proxy=debug cargo r -r -- {{ FLAGS }}
